version: "3.1"

services:
    # Core configuration
    debian:
        container_name: ${CONTAINER_NAME}_debian
        build: '.'
        environment:
             WORKDIR: ${WORKDIR}
        volumes:
            - './:${WORKDIR}:rw'
        restart: always

    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx
        ports:
            - '${NGINX_PORT}:80'
        links:
            - debian
        volumes:
            - './:${WORKDIR}:rw'
            - './docker/nginx/conf/core/nginx.conf:/etc/nginx/conf/nginx.conf:rw'
            - './docker/nginx/conf/app/dev:/etc/nginx/conf.d:rw'
            # - './docker/nginx/conf/app/prod:/etc/nginx/conf.d:ro' -> Uncomment this line for production.
            - './docker/nginx/logs/:/var/log/nginx'
        restart: always

    php-fpm:
        container_name: ${CONTAINER_NAME}_php-fpm
        build: './docker/php'
        environment:
            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
            WORKDIR: '${WORKDIR}'
        ports:
            - '${PHP_PORT}:9000'
        links:
            - debian
        volumes:
            - './:${WORKDIR}:rw'
        restart: always

    # DB configuration
    mysql:
        container_name: ${CONTAINER_NAME}_mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_DATABASE: ${CONTAINER_NAME}
            MYSQL_USER: ${CONTAINER_NAME}
            MYSQL_PASSWORD: '${CONTAINER_NAME}'
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - 'mysql_symfony:/var/lib/mysql'
        restart: always

    mongodb:
        container_name: ${CONTAINER_NAME}_mongodb
        image: mongo
        ports:
          - '${MONGO_PORT}:27017'
        links:
          - debian
        volumes:
          - 'mongo_symfony:/data/db'
        restart: always

    # Testing configuration
    blackfire:
        container_name: ${CONTAINER_NAME}_blackfire
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
        links:
            - php-fpm
        volumes:
            - './:${WORKDIR}:rw'
        restart: always

volumes:
    mysql_symfony:
    mongo_symfony:
